### ISSUE TITLE
Which mgz file  I choose  in the output of Freesurfer?

### ISSUE THREAD

**Issue by enjoy-our-life** [BBillot/hypothalamus_seg#5]
Hi,
In the output of Freesurfer/mri, Which .mgz file is the input file for this program I want to choose？
Thank you for your answer.

**Comment by BBillot** [comment]
I recommend to use nu.mgz.

With that being said, this tool is also available with FreeSurfer >= 7.1:
https://surfer.nmr.mgh.harvard.edu/fswiki/HypothalamicSubunits

If you're using FreeSurfer processed images, I would highly suggest that you use the FreeSurfer implementation of this tool. It's also super easy to use (nearly the same command as the github version). It just assumes you have run recon-all on your subjects, and at this point it will automatically select the nu.mgz file for you.

Hope this helps,
Benjamin
