### ISSUE TITLE
output segmentation in original resolution

### ISSUE THREAD

**Issue by iamnielsjanssen** [BBillot/hypothalamus_seg#7]
Hi thanks for this tool! I understand that when the input images are not equal to 1mm3, the images are internally resampled to 1mm3 and then the segmentation is output in 1mm3 resolution. Would it be possible to obtain the segmentation in the original input resolution? I am using stand-alone version of the program (not the freesurfer one). 

Thanks! Niels

**Comment by BBillot** [comment]
Hi,
I can have a look at this, but first of all, what's the resolution of your data ?
